server:
  port: 8080

spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

feature-toggle:
  resendEmail: true